name: build-develop

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    strategy:
      matrix:
        os: [[windows-latest,x64-windows,msvc]]
        buildType: [Release]
    runs-on: ${{ matrix.os[0] }}

    steps:
      - uses: actions/checkout@v2
      - uses: lukka/get-cmake@latest

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v10
        with:
          vcpkgGitCommitId: 'a0454d6e18b335cf12da34d925538897d598219b'
          setuponly: true

      - name: Checkout submodules
        run: |
          git submodule update --init

      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build-${{ matrix.buildType }}

      - name: Configure CMake
        shell: bash
        working-directory: ${{runner.workspace}}/build-${{ matrix.buildType }}
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{ matrix.buildType }} -DCMAKE_TOOLCHAIN_FILE=$GITHUB_WORKSPACE/vcpkg/scripts/buildsystems/vcpkg.cmake

      - name: Build
        working-directory: ${{runner.workspace}}/build-${{ matrix.buildType }}
        shell: bash
        run: cmake --build . --parallel 2 --config ${{ matrix.buildType }}

      - name: Upload package
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v2
        with:
          name: opengloves.zip
          path: ${{ github.workspace }}/opengloves${{ matrix.os[1] }}.zip